### PR TITLE
CCS-34126: update bv-ui-core dependency for CSP support

### PR DESCRIPTION
**Pull request by bodrovphone**
### Problem

Being a Firebird dependency, scoutfile contains CSP-incompatibly code in bv-ui-core package. 

### Solution
bv-ui-core has been updated in this [#PR33](https://github.com/bazaarvoice/bv-ui-core/pull/93) and a new version released. This would allow us to proceed with the changes needed for Content Security Support. (see epic CCS-34125 for details)
 
### Verification

Not exactly sure how to test this.
I run unit/node modules tests described on Contribution doc here:
https://github.com/bodrovphone/scoutfile/blob/master/CONTRIBUTING.md

node_module_tests
nodeunit-browser
nodeunit
scout-unit-tests

I also generated scoutfile locally. Got neither issues nor errors in the console.

### CODE REVIEW

**Comment by sirugh** [comment]
You're probably best off checking for all uses of the `bv-ui-core` dependency within the `scoutfile` repo. You're jumping two major versions which indicates a breaking change _somewhere_.

**Comment by bodrovphone** [comment]
thanks @sirugh, this makes sense for sure.

My first thought after your suggestion was to check any import from bv-ui-core and then tracing the history of the relevant file changes on bv-ui-core.

Is that the right approach or should I instead dive deeper into this module and its use cases(could be time consuming)?

Thanks again!

**Comment by bodrovphone** [comment]
Hi @tnunamak,

Can you also review this?

I've made some research in UIA-9255 and didn't find any issues with this upgrade. At least with Firebird app, everything works fine. I traced changes as per @sirugh suggestion, and they all seem to be backward compatible. 

There were some enhancements made in [7e3e29](https://github.com/bazaarvoice/bv-ui-core/commit/7e3e29ece10414d07b069aac0cd2a0a5d7dd9c20#diff-24659ab3f41719aa76c59b32627a577f ), [32c7ff](https://github.com/bazaarvoice/bv-ui-core/commit/32c7ffe5cdb8328bdfa5ac52fdf3ca943785dac9#diff-d7e2f1f33f6cad0b0feae844c752f106), [0d9ea5](https://github.com/bazaarvoice/bv-ui-core/commit/0d9ea59b470791ae4b5f72c25a2dfae5a3a27bb8#diff-d7e2f1f33f6cad0b0feae844c752f106) and [8ac7f0](https://github.com/bazaarvoice/bv-ui-core/commit/8ac7f0a0a470276cdc3800a80553cf7a1a971ca4#diff-1d8a6456b4cc3f7ce0a14052aaacff51) since version 0.12.0. I don't see any critical changes though.

Let me know if there is anything I missed or should consider checking apart from what has already been done in UIA-9255.

Thanks in advance!

**Comment by tnunamak** [comment]
The only breaking change I see in bv-ui-core is [removing parseUri](https://github.com/bazaarvoice/bv-ui-core/commit/e39c587cb5499c0d703b868429fdb0e96632ae1d) (1 -> 2). The 0 -> 1 bump wasn't a breaking change, just to align the major version with a production-oriented number per semver guidelines.

Especially since you've done downstream testing, I think this is fine!

**Pull request merged**
